[package]
name = "sum_of_primes"
version = "0.1.0"
authors = ["Ben Ford <ford2bm@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
