[package]
name = "power_digit_sum"
version = "0.1.0"
authors = ["Ben Ford <ford2bm@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.4"
num-traits = "0.2"
num = "0.4"